app/predict/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webpredict.urls'), name='index'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/webpredict/urls.py
from django.urls import path

from .views import KnnSet, KnnAdd, KnnDescription, KnnSelect, RandomForestAdd, RFDescription, RFSelect
from .views import RandomForestSet, XGBoostSet, XGBoostAdd, XGBDescription, XGBSelect, RidgeSet
from .views import VacancyDescription, RidgeDescription, RidgeSelect
from .views import VacancySortId, VacancySortName, VacancySortDate, VacancySortSkills, VacancySortSalary
from .views import VacancyView, VacancyLoad, VacancyPredictRF, VacancyPredictKNN, VacancyPredictXG
from .views import VacancyPredictRidge
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', VacancyView.as_view(), name='index'),
    path('load/', VacancyLoad.as_view(), name='load'),

    path('ridge/', VacancyPredictRidge.as_view(), name='predict_lr'),
    path('random_forest/', VacancyPredictRF.as_view(), name='predict_rf'),
    path('knn/', VacancyPredictKNN.as_view(), name='predict_knn'),
    path('xg/', VacancyPredictXG.as_view(), name='predict_xg'),

    path('id/', VacancySortId.as_view(), name='sort_id'),
    path('name/', VacancySortName.as_view(), name='sort_name'),
    path('date/', VacancySortDate.as_view(), name='sort_date'),
    path('salary/', VacancySortSalary.as_view(), name='sort_salary'),
    path('skills/', VacancySortSkills.as_view(), name='sort_skills'),
    path('<int:pk>/', VacancyDescription.as_view(), name='description'),

    path('set_lr/', RidgeSet.as_view(), name='set_lr'),
    path('set_random_forest/', RandomForestSet.as_view(), name='set_rf'),
    path('set_knn/', KnnSet.as_view(), name='set_knn'),
    path('set_xgb/', XGBoostSet.as_view(), name='set_xgb'),

    path('add_rf/', RandomForestAdd.as_view(), name='add_rf'),
    path('add_knn/', KnnAdd.as_view(), name='add_knn'),
    path('add_xgb/', XGBoostAdd.as_view(), name='add_xgb'),

    path('ridge/<int:pk>', RidgeDescription.as_view(), name='description_lr'),
    path('random_forest/<int:pk>', RFDescription.as_view(), name='description_rf'),
    path('knn/<int:pk>/', KnnDescription.as_view(), name='description_knn'),
    path('xgb/<int:pk>', XGBDescription.as_view(), name='description_xgb'),

    path('select_ridge/<int:pk>', RidgeSelect.as_view(), name='select_lr'),
    path('select_rf/<int:pk>', RFSelect.as_view(), name='select_rf'),
    path('select_knn/<int:pk>', KnnSelect.as_view(), name='select_knn'),
    path('select_xgb/<int:pk>', XGBSelect.as_view(), name='select_xgb'),

]
if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/webpredict/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Vacancy(models.Model):
    id_hh = models.IntegerField()
    name = models.CharField(max_length=255)
    area = models.CharField(max_length=30, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    skills = models.TextField()
    employer = models.CharField(max_length=255, blank=True, null=True)
    employment = models.CharField(max_length=50, blank=True, null=True)
    schedule = models.CharField(max_length=50, blank=True, null=True)
    salary = models.IntegerField(blank=True, default=0, null=True)
    predict_salary = models.IntegerField(blank=True, default=0, null=True)
    date = models.DateField()

    class Meta:
        db_table = 'vacancy'
        verbose_name_plural = 'Вакансии'
        verbose_name = 'Вакансия'
        ordering = ['id_hh']


class KnnModel(models.Model):
    PARAMS_WEIGHTS = (
        ("uniform", "uniform"),
        ("distance", "distance"),
    )
    PARAMS_P = (
        (1, "manhattan distance"),
        (2, "euclidean distance"),
    )
    name = models.CharField(max_length=10)
    neighbors = models.IntegerField(default=5)
    weights = models.CharField(max_length=10, choices=PARAMS_WEIGHTS, default="U")
    p = models.IntegerField(choices=PARAMS_P, default=2)
    mae = models.FloatField(default=0)
    mse = models.FloatField(default=0)
    file_model = models.FileField(default=None)

    class Meta:
        db_table = 'knn'
        verbose_name_plural = 'Модели К-ближайших соседей'
        verbose_name = 'Модель К-ближайших соседей'
        ordering = ['id']


class RandomForestModel(models.Model):
    PARAMS_FEATURES = (
        ("log2", "log2"),
        ("sqrt", "sqrt"),
        ("auto", "auto"),
    )
    name = models.CharField(max_length=10)
    estimators = models.IntegerField(default=100)
    max_features = models.CharField(max_length=4, choices=PARAMS_FEATURES, default="auto")
    min_samples_split = models.IntegerField(default=2)
    min_samples_leaf = models.IntegerField(default=1)
    mae = models.FloatField(default=0)
    mse = models.FloatField(default=0)
    file_model = models.FileField(default=None)

    class Meta:
        db_table = 'randomforest'
        verbose_name_plural = 'Модели случайного леса'
        verbose_name = 'Модель случайного леса'
        ordering = ['id']


class XGBoostModel(models.Model):
    name = models.CharField(max_length=10)
    estimators = models.IntegerField(default=100)
    max_depth = models.IntegerField(default=6)
    colsample_bytree = models.FloatField(default=1.0)
    alpha = models.FloatField(default=0.01)
    mae = models.FloatField(default=0)
    mse = models.FloatField(default=0)
    file_model = models.FileField(default=None)

    class Meta:
        db_table = 'xgboost'
        verbose_name_plural = 'Модели градиентного бустинга'
        verbose_name = 'Модель градиентного бустинга'
        ordering = ['id']


class RidgeModel(models.Model):
    name = models.CharField(max_length=10)
    mae = models.FloatField(default=0)
    mse = models.FloatField(default=0)
    file_model = models.FileField(default=None)

    class Meta:
        db_table = 'ridge'
        verbose_name_plural = 'Модели линейной регресии'
        verbose_name = 'Модель линейной регресии'
        ordering = ['id']

app/webpredict/views.py
import datetime

from django.core.files import File
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.list import ListView
from functions.knn import get_predict_knn
from functions.loadvacansies import get_vacancies
from functions.ml_models import Knn, RandomForest, XGBoostReg, Ridge_reg
from functions.randomforest import get_predict_rf
from functions.ridge import get_predict_lr
from functions.xgboost import get_predict_xg

from .forms import VacancyForm, KnnModelForm, RandomForestModelForm, XGBoostModelForm, RidgeModelForm
from .models import Vacancy, KnnModel, RandomForestModel, XGBoostModel, RidgeModel


# Create your views here.

def add_new_vacancy(list_vacancies: list):
    for parameter_vacancy in list_vacancies:
        new_vacancy = Vacancy()
        if not Vacancy.objects.filter(id_hh=parameter_vacancy[0]).exists():
            new_vacancy.id_hh = parameter_vacancy[0]
            new_vacancy.name = parameter_vacancy[1]
            new_vacancy.area = parameter_vacancy[2]
            new_vacancy.employer = parameter_vacancy[3]
            new_vacancy.schedule = parameter_vacancy[4]
            new_vacancy.employment = parameter_vacancy[5]
            new_vacancy.description = parameter_vacancy[6]
            new_vacancy.skills = parameter_vacancy[7]
            new_vacancy.salary = parameter_vacancy[8]
            new_vacancy.date = datetime.date.today()
            new_vacancy.save()


def add_predict_salary(predict_salary: zip):
    for id_hh, predict in predict_salary:
        vacancy = Vacancy.objects.get(id_hh=id_hh)
        vacancy.predict_salary = predict
        vacancy.save()


def create_base_model():
    if not RidgeModel.objects.filter(name="base").exists():
        new_lr = RidgeModel()
        new_lr.name = "base"
        with open("./media/ml_models_save/base/lr.save", "rb") as file:
            new_lr.file_model = File(file)
            new_lr.save()
    if not KnnModel.objects.filter(name="base").exists():
        new_knn = KnnModel()
        new_knn.name = "base"
        new_knn.weights = "distance"
        new_knn.neighbors = 11
        new_knn.p = 2
        with open("./media/ml_models_save/base/knn.save", "rb") as file:
            new_knn.file_model = File(file)
            new_knn.save()
    if not RandomForestModel.objects.filter(name="base").exists():
        new_rf = RandomForestModel()
        new_rf.name = "base"
        new_rf.estimators = 100
        new_rf.min_samples_leaf = 1
        new_rf.max_features = 'sqrt'
        with open("./media/ml_models_save/base/rf.save", "rb") as file:
            new_rf.file_model = File(file)
            new_rf.save()
    if not XGBoostModel.objects.filter(name="base").exists():
        new_xgb = XGBoostModel()
        new_xgb.name = "base"
        new_xgb.estimators = "500"
        new_xgb.max_depth = 3
        new_xgb.colsample_bytree = 0.2
        new_xgb.alpha = 0.01
        with open("./media/ml_models_save/base/xgb.save", "rb") as file:
            new_xgb.file_model = File(file)
            new_xgb.save()


class VacancyView(ListView):
    template_name = 'webpredict/index.html'
    model = Vacancy
    success_url = reverse_lazy('index')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vacancies"] = Vacancy.objects.order_by('id')
        return context


class VacancyLoad(ListView):
    template_name = 'webpredict/index.html'
    model = Vacancy
    success_url = reverse_lazy('load')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        create_base_model()
        vacancies = Vacancy.objects.all()
        if not vacancies.exists():
            list_vacancies = get_vacancies(True)
            add_new_vacancy(list_vacancies)
        else:
            list_vacancies = get_vacancies(False)
            add_new_vacancy(list_vacancies)

        context["vacancies"] = Vacancy.objects.order_by('id')
        return context


class VacancyPredictRidge(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('predict_lr')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vacancies = Vacancy.objects.order_by('id')
        if vacancies.exists():
            predict_salary = get_predict_lr(vacancies)
            add_predict_salary(predict_salary)
        vacancies = Vacancy.objects.order_by('id')
        context["vacancies"] = vacancies
        return context


class VacancyPredictRF(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('predict_rf')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vacancies = Vacancy.objects.order_by('id')
        if vacancies.exists():
            predict_salary = get_predict_lr(vacancies)
            add_predict_salary(predict_salary)
        vacancies = Vacancy.objects.order_by('id')
        context["vacancies"] = vacancies
        return context


class VacancyPredictKNN(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('predict_knn')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vacancies = Vacancy.objects.order_by('id')
        if vacancies.exists():
            predict_salary = get_predict_lr(vacancies)
            add_predict_salary(predict_salary)
        vacancies = Vacancy.objects.order_by('id')
        context["vacancies"] = vacancies
        return context


class VacancyPredictXG(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('predict_xg')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vacancies = Vacancy.objects.order_by('id')
        if vacancies.exists():
            predict_salary = get_predict_lr(vacancies)
            add_predict_salary(predict_salary)
        vacancies = Vacancy.objects.order_by('id')
        context["vacancies"] = vacancies
        return context


class VacancySortId(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('sort_id')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vacancies"] = Vacancy.objects.order_by('id')
        return context


class VacancySortDate(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('sort_date')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vacancies"] = Vacancy.objects.order_by('-date')
        return context


class VacancySortName(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('sort_name')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vacancies"] = Vacancy.objects.order_by('name')
        return context


class VacancySortSkills(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('sort_skills')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vacancies"] = Vacancy.objects.order_by('skills')
        return context


class VacancySortSalary(ListView):
    template_name = "webpredict/index.html"
    model = Vacancy
    success_url = reverse_lazy('sort_salary')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["vacancies"] = Vacancy.objects.order_by('salary')
        return context


class VacancyDescription(UpdateView):
    template_name = "webpredict/description.html"
    model = Vacancy
    form_class = VacancyForm
    success_url = reverse_lazy('index')

    def get_queryset(self, **kwargs):
        return Vacancy.objects.filter(id=self.kwargs['pk'])


class RidgeSet(ListView):
    template_name = "webpredict/ridge.html"
    model = RidgeModel
    success_url = reverse_lazy('set_lr')
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ridge_models = RidgeModel.objects.all()
        context["lrs"] = ridge_models
        return context


class KnnSet(ListView):
    template_name = "webpredict/knn.html"
    model = KnnModel
    success_url = reverse_lazy('set_knn')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if Vacancy.objects.all().exists():
            knn_models = KnnModel.objects.all()
            context["knns"] = knn_models
        else:
            context["knns"] = []
        return context


class RandomForestSet(ListView):
    template_name = "webpredict/randomforest.html"
    model = KnnModel
    success_url = reverse_lazy('set_rf')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if Vacancy.objects.all().exists():
            rf_models = RandomForestModel.objects.all()
            context["rfs"] = rf_models
        else:
            context["rfs"] = []
        return context


class XGBoostSet(ListView):
    template_name = "webpredict/xgboost.html"
    model = KnnModel
    success_url = reverse_lazy('set_xgb')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

app/webpredict/templates/webpredict/description.html
{% extends 'layout/basic.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}

    <form method="post" class="text-center">
        {% csrf_token %}
        {#        {{ form.as_p }}#}
        <input type="text" class="vacancy form-control text-center" name="{{ form.name.name }}"
               id="{{ form.name.id_for_label }}" value="{{ form.name.value }}">
        <div class="form-group">
            <input type="text" class="form-control" name="{{ form.area.name }}"
                   id="{{ form.area.id_for_label }}" value="{{ form.area.value }}">
            <input type="text" class="form-control" name="{{ form.employer.name }}"
                   id="{{ form.employer.id_for_label }}" value="{{ form.employer.value }}">
            <input type="text" class="form-control" name="{{ form.employment.name }}"
                   id="{{ form.employment.id_for_label }}" value="{{ vacancy.employment }}">
            <input type="text" class="form-control" name="{{ form.schedule.name }}"
                   id="{{ form.schedule.id_for_label }}" value="{{ form.schedule.value }}">
        </div>
        <div class="form-group">
            <label for="{{ form.skills.id_for_label }}" class="form-label">Навыки</label>
            <textarea class="form-control" name="{{ form.skills.name }}"
                      id="{{ form.skills.id_for_label }}">{{ form.skills.value }}</textarea>
            <br/>
            <label for="{{ form.description.id_for_label }}" class="form-label">Описание</label>
            <textarea class="form-control" name="{{ form.description.name }}"
                      id="{{ form.description.id_for_label }}">{{ form.description.value }}</textarea>
            <br/>
        </div>

        <div class="form-group">
            <label for="id_salary" class="form-label">Заработная плата</label>
            <input type="number" class="form-control" name="{{ form.salary.name }}" id="id_salary"
                   value="{{ form.salary.value }}">
        </div>
        <div class="text-center">
            <br/>
            <button type="submit" class="my-submit">Изменить</button>
        </div>
    </form>

{% endblock %}

app/webpredict/templates/webpredict/description_knn.html
{% extends 'layout/basic.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <form method="post" class="text-center col-lg-3 offset-lg-0">
                {% csrf_token %}
                {#        {{ form.as_p }}#}
                <div class="form-group row justify-content-center text-center">
                    <label for="{{ form.name.id_for_label }}" class="form-label">Имя модели</label>
                    <input type="text" class="form-control text-center" name="{{ form.name.name }}"
                           id="{{ form.name.id_for_label }}" value="{{ form.name.value }}"readonly>
                    <label for="{{ form.neighbors.id_for_label }}" class="form-label">Число соседей</label>
                    <input type="number" class="form-control text-center" name="{{ form.neighbors.name }}"
                           id="{{ form.neighbors.id_for_label }}" value="{{ form.neighbors.value }}" readonly>
                    <label for="{{ form.weights.id_for_label }}" class="form-label">Функция веса</label>
                    <input type="text" class="form-control text-center" name="{{ form.weights.name }}"
                           id="{{ form.weights.id_for_label }}" value="{{ form.weights.value }}" readonly>
                    <label for="{{ form.p.id_for_label }}" class="form-label">Метрика</label>
                    <input type="number" class="form-control text-center" name="{{ form.p.name }}"
                           id="{{ form.p.id_for_label }}" value="{{ form.p.value }}" readonly>
                    <br/>
                </div>
                <br/>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod1" value="cross"
                           checked/>
                    <label class="form-check-label" for="radiomethod1">Кросс-валидация</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod2" value="split"/>
                    <label class="form-check-label" for="radiomethod2">Обучение на выборках</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod3" value="all"/>
                    <label class="form-check-label" for="radiomethod3">Обучение на всех данных</label>
                </div>

                <div class="text-center">
                    <br/>
                    <button type="submit" class="my-submit">Обучить</button>
                </div>
            </form>

        </div>
    </div>

{% endblock %}

app/webpredict/templates/webpredict/description_lr.html
{% extends 'layout/basic.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <form method="post" class="text-center col-lg-3 offset-lg-0">
                {% csrf_token %}
                <div class="form-group row justify-content-center text-center">
                    <label for="{{ form.name.id_for_label }}" class="form-label">Имя модели</label>
                    <input type="text" class="form-control text-center" name="{{ form.name.name }}"
                           id="{{ form.name.id_for_label }}" value="{{ form.name.value }}"readonly>
                    <br/>
                </div>
                <br/>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod1" value="cross"
                           checked/>
                    <label class="form-check-label" for="radiomethod1">Кросс-валидация</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod2" value="split"/>
                    <label class="form-check-label" for="radiomethod2">Обучение на выборках</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod3" value="all"/>
                    <label class="form-check-label" for="radiomethod3">Обучение на всех данных</label>
                </div>

                <div class="text-center">
                    <br/>
                    <button type="submit" class="my-submit">Обучить</button>
                </div>
            </form>

        </div>
    </div>

{% endblock %}

app/webpredict/templates/webpredict/description_rf.html
{% extends 'layout/basic.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <form method="post" class="text-center col-lg-3 offset-lg-0">
                {% csrf_token %}
                {#        {{ form.as_p }}#}
                <div class="form-group row justify-content-center text-center">
                    <label for="{{ form.name.id_for_label }}" class="form-label">Название</label>
                    <input type="text" class="form-control text-center" name="{{ form.name.name }}"
                           id="{{ form.name.id_for_label }}" value="{{ form.name.value }}" readonly>
                    <label for="{{ form.estimators.id_for_label }}" class="form-label">Число деревьев</label>
                    <input type="number" class="form-control text-center" name="{{ form.estimators.name }}"
                           id="{{ form.estimators.id_for_label }}" value="{{ form.estimators.value }}" readonly>
                    <label for="{{ form.max_features.id_for_label }}" class="form-label">Число признаков</label>
                    <input type="text" class="form-control text-center" name="{{ form.max_features.name }}"
                           id="{{ form.max_features.id_for_label }}" value="{{ form.max_features.value }}" readonly>
                    <label for="{{ form.min_samples_split.id_for_label }}" class="form-label">Число сэмплов при делении</label>
                    <input type="number" class="form-control text-center" name="{{ form.min_samples_split.name }}"
                           id="{{ form.min_samples_split.id_for_label }}" value="{{ form.min_samples_split.value }}" readonly>
                    <label for="{{ form.min_samples_leaf.id_for_label }}" class="form-label">Число сэмплов в узле</label>
                    <input type="number" class="form-control text-center" name="{{ form.min_samples_leaf.name }}"
                           id="{{ form.min_samples_leaf.id_for_label }}" value="{{ form.min_samples_leaf.value }}" readonly>
                </div>
                <br/>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod1" value="cross"
                           checked/>
                    <label class="form-check-label" for="radiomethod1">Кросс-валидация</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod2" value="split"/>
                    <label class="form-check-label" for="radiomethod2">Обучение на выборках</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod3" value="all"/>
                    <label class="form-check-label" for="radiomethod3">Обучение на всех данных</label>
                </div>

                <div class="text-center">
                    <br/>
                    <button type="submit" class="my-submit">Обучить</button>
                </div>
            </form>

        </div>
    </div>

{% endblock %}

app/webpredict/templates/webpredict/description_xgb.html
{% extends 'layout/basic.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <form method="post" class="text-center col-lg-3 offset-lg-0">
                {% csrf_token %}
                {#        {{ form.as_p }}#}
                <div class="form-group row justify-content-center text-center">
                    <label for="{{ form.name.id_for_label }}" class="form-label">Название</label>
                    <input type="text" class="form-control text-center" name="{{ form.name.name }}"
                           id="{{ form.name.id_for_label }}" value="{{ form.name.value }}" readonly>
                    <label for="{{ form.estimators.id_for_label }}" class="form-label">Число деревьев</label>
                    <input type="number" class="form-control text-center" name="{{ form.estimators.name }}"
                           id="{{ form.estimators.id_for_label }}" value="{{ form.estimators.value }}" readonly>
                    <label for="{{ form.max_depth.id_for_label }}" class="form-label">Глубина деревьев</label>
                    <input type="text" class="form-control text-center" name="{{ form.max_depth.name }}"
                           id="{{ form.max_depth.id_for_label }}" value="{{ form.max_depth.value }}" readonly>
                    <label for="{{ form.colsample_bytree.id_for_label }}" class="form-label">Число признаков</label>
                    <input type="number" step="0.1" class="form-control text-center"
                           name="{{ form.colsample_bytree.name }}"
                           id="{{ form.colsample_bytree.id_for_label }}" value="{{ form.colsample_bytree.value }}"
                           readonly>
                    <label for="{{ form.alpha.id_for_label }}" class="form-label">Скорость обучения</label>
                    <input type="number" class="form-control text-center" name="{{ form.alpha.name }}"
                           id="{{ form.alpha.id_for_label }}" value="{{ form.alpha.value }}" readonly>
                </div>
                <br/>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod1" value="cross"
                           checked/>
                    <label class="form-check-label" for="radiomethod1">Кросс-валидация</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod2" value="split"/>
                    <label class="form-check-label" for="radiomethod2">Обучение на выборках</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="radiomethod" id="radiomethod3" value="all"/>
                    <label class="form-check-label" for="radiomethod3">Обучение на всех данных</label>
                </div>

                <div class="text-center">
                    <br/>
                    <button type="submit" class="my-submit">Обучить</button>
                </div>
            </form>

        </div>
    </div>

{% endblock %}

app/webpredict/templates/webpredict/knn.html
{% extends 'layout/basic.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <h1>Модели К-ближайших соседей <a class="my-link" href="{% url 'add_knn' %}">[+]</a></h1>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Число соседей</th>
            <th scope="col">Функция веса</th>
            <th scope="col">Параметр мощности метрики</th>
            <th scope="col">MAE</th>
            <th scope="col">MSE</th>
            <th scope="col">Выбрать</th>
        </tr>
        </thead>
        <tbody>
        {% for knn in knns %}
            <tr>
                <th scope="row"><a class="nav-link my-link"
                                   href="{% url 'description_knn' pk=knn.id %}"> {{ knn.name }}</a></th>
                <td>{{ knn.neighbors }}</td>
                <td>{{ knn.weights }}</td>
                <td>{{ knn.p }}</td>
                <td>{{ knn.mae }}</td>
                <td>{{ knn.mse }}</td>
                {% if knn.file_model %}
                <td><a class="my-link" href="{% url 'select_knn' pk=knn.id%}">Выбрать</a></td>
                {% else %}
                <td>-</td>
                {% endif %}



            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}